// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCPUUsage():Promise<number>;

export function GetDiskUsage():Promise<number>;

export function GetRamUsage():Promise<main.ramInfo>;

export function Greet(arg1:string):Promise<string>;
